### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by TBD** [Svalorzen/UbiShell#1]
Chrome 66/OSX crashes on startup

if I inspect the background page from the Extension page here are the errors:

```
Uncaught ReferenceError: jQuery is not defined
    at cmdutils.js:8
commands.js:4 Uncaught TypeError: Cannot read property 'CreateCommand' of undefined
    at commands.js:4
searchcursor.js:10 Uncaught ReferenceError: CodeMirror is not defined
    at searchcursor.js:10
    at searchcursor.js:11
```

hope it helps

**Comment by Svalorzen** [comment]
Thanks! It seems I made a mess when adding the scripts we use directly in the manifest. It seems Chrome loads them in order, and jquery appeared after the cmdutils script so it crashed.

I'm testing it now, I'll push a fix in a little bit!

**Comment by Svalorzen** [comment]
Hey, just wanted to let you know that I fixed it. Let me know if it works so I can close this issue. =)

**Comment by TBD** [comment]
works now. #1 can be closed for now.
